### ISSUE TITLE
Implementatie van Spaarstand voor verwarming

### ISSUE THREAD

**Issue by rapedapeda** [rapedapeda/hassio#11]
**Omschrijving:**
Deze functionaliteit is bedoeld om de verwarming in kamers te beheren door het automatisch aanpassen van de temperatuur op basis van afwezigheid. Het doel is om de verwarming energiezuinig te maken door de temperatuur in verschillende fasen te verlagen na vertrek, terwijl het huis niet te snel afkoelt en je bij thuiskomst niet in een koud huis hoeft te komen. Dit zal helpen om het comfort te verhogen, zonder excessief veel energie te gebruiken.

**Functionaliteit:**
De verwarming moet na het verlaten van de woning gefaseerd afkoelen, en dit moet per kamer instelbaar zijn met verschillende vertragingen en temperatuurverlagingen.

1. **Spaarstand configuratie per kamer:**
   Elke ruimte heeft een **spaarstand** configuratie, die bestaat uit:
   - **Delay**: De tijd in minuten na het verlaten van de woning voordat de temperatuur begint te dalen.
   - **Delta**: De temperatuurdaling ten opzichte van de **target_temp** (de gewenste temperatuur voor de ruimte) na de vertraging.

2. **Fasen voor temperatuurverlaging:**
   - **Direct na afwezigheid**: De temperatuur daalt direct naar de **target_temp van de eerste spaarstand**.
   - **Na 30 minuten afwezigheid**: De temperatuur daalt naar de **target_temp van de tweede spaarstand**.
   - **Na 120 minuten afwezigheid**: De verwarming wordt **uitgeschakeld**.

3. **Instellingen voor vertraging en temperatuurverlagingen:**
   De **delay** en **delta** kunnen per kamer worden ingesteld. Een voorbeeld van een configuratie per ruimte:
   - **Delay 1 (0-30 minuten)**: Temperatuurdaling tot **0.5 graden** onder de **target_temp**.
   - **Delay 2 (30-120 minuten)**: Temperatuurdaling tot **1 graad** onder de **target_temp**.
   
4. **Voorbeeldconfiguratie**:
   - De **spaarstand** moet als een lijst van objecten per kamer gedefinieerd worden. Hier kunnen de **delay** en **delta** voor elke fase worden ingesteld.

**Voorbeeldconfiguratie in YAML**:

```yaml
Climate:
  module: auto_climate
  class: AutoClimate
  house_presence: alarm.alarm_home
  zones:
    woonkamer:
      thermostat: climate.woonkamer
      room_presence: binary_sensor.aanwezigheid_woonkamer
      default_target_temp: 21.0
      time_schedules:
        - days: saturday, sunday
          start: '09:00'
          end: '21:00'
          target_temp: 19
      savings_mode:
        - delay: 0   # Direct na afwezigheid
          delta: -0.5  # Temperatuurdaling naar target_temp - 0.5
        - delay: 30   # Na 30 minuten
          delta: -1    # Temperatuurdaling naar target_temp - 1
```

**Gedrag**:
- **Na vertrek**: De verwarming wordt direct verlaagd naar **target_temp - 0.5** (fase 1).
- **Na 30 minuten**: De verwarming wordt verder verlaagd naar **target_temp - 1.0** (fase 2).
- **Na 120 minuten**: De verwarming wordt volledig uitgeschakeld.

**Doelen**:
- Energie besparen door de temperatuur gefaseerd te verlagen.
- Het comfort behouden door niet te snel de verwarming uit te schakelen.
- Flexibiliteit bieden per ruimte door vertragingen en temperatuurinstellingen te configureren.

**Verwachte voordelen**:
- Besparing op energieverbruik zonder het comfort in de ruimte te veel te verminderen.
- De mogelijkheid om het systeem per ruimte af te stemmen, zodat je specifieke instellingen per kamer kunt toepassen.
- De temperatuur verlaagt geleidelijk, wat helpt om het huis sneller op te warmen wanneer je weer thuiskomt.
